### PR TITLE
new balls have auto_admin set to true

### PR DESCRIPTION
**Pull request by dmepham**
https://dataxu.atlassian.net/browse/BT-2054

tests ongoing

### CODE REVIEW

**Comment by babineaum** [comment]
:shipit:  @dmepham thanks!

**Comment by babineaum** [comment]
whats the process here, do we build a new image?

**Comment by dmepham** [comment]
yeah, we should build a new image with this and make sure the deploy comes up fine

**Comment by dmepham** [comment]
building new image here https://jenkins.devaws.dataxu.net/job/qatools_create_ami/19/

**Comment by babineaum** [comment]
do you mind spearheading this? i can support if there are issues.

**Comment by dmepham** [comment]
sure

**Comment by dmepham** [comment]
closing

**Pull request closed without merging**
